INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('john.doe@gmail.com', 'Senior Recruiter', 'https://linkedin.com/in/johndoe');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('jane.smith@gmail.com', 'Recruiter', 'https://linkedin.com/in/janesmith');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('michael.brown@gmail.com', 'Junior Recruiter', 'https://linkedin.com/in/michaelbrown');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('emily.jones@gmail.com', 'Recruitment Manager', 'https://linkedin.com/in/emilyjones');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('david.wilson@gmail.com', 'Recruitment Specialist', 'https://linkedin.com/in/davidwilson');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('frank.moore@gmail.com', 'Senior Recruiter', 'https://linkedin.com/in/frankmoore');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('grace.taylor@gmail.com', 'Recruiter', 'https://linkedin.com/in/gracetaylor');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('hank.wilson@gmail.com', 'Junior Recruiter', 'https://linkedin.com/in/hankwilson');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('ivy.harris@gmail.com', 'Recruitment Manager', 'https://linkedin.com/in/ivyharris');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('jack.clark@gmail.com', 'Recruitment Specialist', 'https://linkedin.com/in/jackclark');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('alice.brown@gmail.com', 'Senior Recruiter', 'https://linkedin.com/in/alicebrown');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('bob.johnson@gmail.com', 'Recruiter', 'https://linkedin.com/in/bobjohnson');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('carol.davis@gmail.com', 'Junior Recruiter', 'https://linkedin.com/in/caroldavis');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('dave.martin@gmail.com', 'Recruitment Manager', 'https://linkedin.com/in/davemartin');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('eve.evans@gmail.com', 'Recruitment Specialist', 'https://linkedin.com/in/eveevans');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('sarah.moore@gmail.com', 'Senior Recruiter', 'https://linkedin.com/in/sarahmoore');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('james.taylor@gmail.com', 'Recruiter', 'https://linkedin.com/in/jamestaylor');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('linda.white@gmail.com', 'Junior Recruiter', 'https://linkedin.com/in/lindawhite');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('robert.harris@gmail.com', 'Recruitment Manager', 'https://linkedin.com/in/robertharris');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('patricia.clark@gmail.com', 'Recruitment Specialist', 'https://linkedin.com/in/patriciaclark');
INSERT INTO tbl_JQ_Recruiter (email, position, LinkedInProfile) VALUES ('amarsunuwar09@gmail.com', 'Recruitment Specialist', 'https://linkedin.com/in/amarsunuwar');