INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('john.doe@gmail.com', 'John', 'Doe', '1234567890', 'India', 'Telangana', 'Hyderabad');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('jane.smith@gmail.com', 'Jane', 'Smith', '2345678901', 'India', 'Maharashtra', 'Pune');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('michael.brown@gmail.com', 'Michael', 'Brown', '3456789012', 'India', 'Madhya Pradesh', 'Indore');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('emily.jones@gmail.com', 'Emily', 'Jones', '4567890123', 'India', 'Delhi', 'Delhi');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('david.wilson@gmail.com', 'David', 'Wilson', '5678901234', 'India', 'Haryana', 'Gurgaon');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('sarah.moore@gmail.com', 'Sarah', 'Moore', '6789012345', 'India', 'Karnataka', 'Bengaluru');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('james.taylor@gmail.com', 'James', 'Taylor', '7890123456', 'India', 'Tamil Nadu', 'Chennai');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('linda.white@gmail.com', 'Linda', 'White', '8901234567', 'India', 'Maharashtra', 'Mumbai');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('robert.harris@gmail.com', 'Robert', 'Harris', '9012345678', 'India', 'Odisha', 'Bhubaneshwar');
INSERT INTO tbl_JQ_User (email, first_name, last_name, phone, country, state, city) VALUES ('patricia.clark@gmail.com', 'Patricia', 'Clark', '0123456789', 'India', 'West Bengal', 'Kolkata');
